#ifndef _PROFILER_H_
#define _PROFILER_H_

// generate profiler category enums and names
#define PROFILER_FOREACH(PROFILER) \
  PROFILER(APPLICATION) \
  PROFILER(INIT_PER_PAR) \
  PROFILER(ITER1PAR) \
  PROFILER(SAVE_VALS) \
  PROFILER(CLEAR_PER_PAR) \
  PROFILER(NUM_PROFILERS)

#define PROFILER_GENERATE_ENUM(ENUM) ENUM,
 
typedef enum {
  PROFILER_FOREACH(PROFILER_GENERATE_ENUM)
} PROFILER;

#define PROFILER_GENERATE_NAME(STRING) #STRING,

static const char* PROFILER_NAME[] = {
    PROFILER_FOREACH(PROFILER_GENERATE_NAME)
};

#endif
